### ISSUE TITLE
IDK

### ISSUE THREAD

**Issue by Spitik** [typekcz/beepboop-steam#1]
> beepboop@1.0.0 start /Users/kubo/Desktop/beepboop-steam-master
> node index

Start:
Unhandled Promise Rejection Promise {
  <rejected> { Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432 } } { Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }
login
Page log: Loading CM List
Page log: Connecting socket to host CM01-VIE.cm.steampowered.com:27020
Page log: Connected socket to host CM01-VIE.cm.steampowered.com:27020
Page log: Ready To Render promises succeeded
Page log: FriendsUI ready to render after 2742.9549999942537ms
Unhandled Promise Rejection Promise {
  <rejected> Error: Evaluation failed: TypeError: Cannot read property 'chatRoomList' of undefined
      at __puppeteer_evaluation_script__:3:64
      at ExecutionContext.evaluateHandle (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    -- ASYNC --
      at ExecutionContext.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:108:27)
      at ExecutionContext.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
      at ExecutionContext.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:109:23)
      at DOMWorld.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/DOMWorld.js:105:20)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    -- ASYNC --
      at Frame.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:108:27)
      at Page.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/Page.js:815:43)
      at Page.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:109:23)
      at SteamChat.openGroup (/Users/kubo/Desktop/beepboop-steam-master/steamchat.js:243:19)
      at process._tickCallback (internal/process/next_tick.js:68:7) } Error: Evaluation failed: TypeError: Cannot read property 'chatRoomList' of undefined
    at __puppeteer_evaluation_script__:3:64
    at ExecutionContext.evaluateHandle (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:108:27)
    at ExecutionContext.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:109:23)
    at DOMWorld.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/DOMWorld.js:105:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/Page.js:815:43)
    at Page.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:109:23)
    at SteamChat.openGroup (/Users/kubo/Desktop/beepboop-steam-master/steamchat.js:243:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Evaluation failed: TypeError: Cannot read property 'voiceRoomList' of undefined
    at __puppeteer_evaluation_script__:3:34
    at ExecutionContext.evaluateHandle (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:108:27)
    at ExecutionContext.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:109:23)
    at DOMWorld.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/DOMWorld.js:105:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.evaluate (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/Page.js:815:43)
    at Page.<anonymous> (/Users/kubo/Desktop/beepboop-steam-master/node_modules/puppeteer/lib/helper.js:109:23)
    at SteamChat.joinVoiceChannel (/Users/kubo/Desktop/beepboop-steam-master/steamchat.js:326:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Page log: Failed to load resource: the server responded with a status of 404 ()

**Comment by typekcz** [comment]
Bad configuration. Couldn't connect to db. Couldn't find group chat.
Simplest way to configure BeepBoop is to make config.json in project root and use template from readme.
