### ISSUE TITLE
Error: Could not find browser revision 818858

### ISSUE THREAD

**Issue by hokagay7** [typekcz/beepboop-steam#22]
```
2023-05-13T06:39:05.153730976Z stdout F  ___               ___                
2023-05-13T06:39:05.15377446Z stdout F | _ ) ___ ___ _ __| _ ) ___  ___ _ __ 
2023-05-13T06:39:05.153778856Z stdout F | _ \/ -_) -_) '_ \ _ \/ _ \/ _ \ '_ \
2023-05-13T06:39:05.153781932Z stdout F |___/\___\___| .__/___/\___/\___/ .__/
2023-05-13T06:39:05.153784496Z stdout F              |_| v2.0.1         |_|  
2023-05-13T06:39:05.253731572Z stdout F 2023-05-13 06:39:05,252 INFO spawned: 'steam' with pid 246
2023-05-13T06:39:06.256978298Z stdout F 2023-05-13 06:39:06,256 INFO success: steam entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-13T06:39:06.456013581Z stdout F Cannot read properties of undefined (reading 'none')
2023-05-13T06:39:06.456333147Z stdout F Initializing Steam web API.
2023-05-13T06:39:06.752172158Z stdout F Unhandled Promise Rejection Promise {
2023-05-13T06:39:06.752207915Z stdout F   <rejected> Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
2023-05-13T06:39:06.752213208Z stdout F       at ChromeLauncher.launch (/beepboop/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)
2023-05-13T06:39:06.752216864Z stdout F       at async SteamBrowserApi.init (file:///beepboop/src/steam-api/steam-browser-api.js:52:19)
2023-05-13T06:39:06.752220752Z stdout F       at async BeepBoop.init (file:///beepboop/src/beepboop.js:54:3)
2023-05-13T06:39:06.752224408Z stdout F       at async Main.main (file:///beepboop/src/main.js:23:3)
2023-05-13T06:39:06.752227905Z stdout F } Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
2023-05-13T06:39:06.752231295Z stdout F     at ChromeLauncher.launch (/beepboop/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)
2023-05-13T06:39:06.752234151Z stdout F     at async SteamBrowserApi.init (file:///beepboop/src/steam-api/steam-browser-api.js:52:19)
2023-05-13T06:39:06.75223791Z stdout F     at async BeepBoop.init (file:///beepboop/src/beepboop.js:54:3)
2023-05-13T06:39:06.752240728Z stdout F     at async Main.main (file:///beepboop/src/main.js:23:3)
2023-05-13T06:39:08.455573731Z stdout F 2023-05-13 06:39:08,455 INFO exited: steam (exit status 1; not expected)
2023-05-13T06:39:09.459659335Z stdout F 2023-05-13 06:39:09,459 INFO spawned: 'steam' with pid 258
2023-05-13T06:39:10.458997872Z stdout F 2023-05-13 06:39:10,458 INFO success: steam entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-13T06:39:10.553252947Z stdout F 2023-05-13 06:39:10,552 INFO exited: steam (exit status 1; not expected)
```

Im trying to host beepboop on Northflank and Render, both output the same error. 
I ran `PUPPETEER_PRODUCT=firefox npm install` and the error still persist.

**Comment by typekcz** [comment]
Because voice chat in browser wasn't working, I implemented it so that it is interfacing directly with Steam client.
Supplied Docker image is designed to run the Steam client and not for running a browser.
So you should leave `MODE=client` in docker-compose.yml.
If you want to run in `MODE=web` you can't use Docker image that is in this repo.

I don't know if web mode is working properly, since it was a long time ago that I used it.
But looks like voice chat in browser is working again, so I will revisit the web implementation and create separate docker-compose for running in web mode.

**Comment by hokagay7** [comment]
Now it gave me this error

```
May 13 06:09:02 PM  Initializing Steam client API.
May 13 06:09:03 PM  Your service is live 🎉
May 13 06:09:51 PM  2023-05-13 10:09:51,372 INFO exited: steam (exit status 1; not expected)
May 13 06:09:52 PM  2023-05-13 10:09:52,380 INFO spawned: 'steam' with pid 413
May 13 06:09:53 PM  2023-05-13 10:09:53,382 INFO success: steam entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
May 13 06:10:04 PM  2023-05-13 10:10:04,671 WARN received SIGTERM indicating exit request
May 13 06:10:04 PM  2023-05-13 10:10:04,683 CRIT unknown problem killing lxpanel (32):Traceback (most recent call last):
May 13 06:10:04 PM    File "/usr/lib/python3/dist-packages/supervisor/process.py", line 466, in kill
May 13 06:10:04 PM      options.kill(pid, sig)
May 13 06:10:04 PM    File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1298, in kill
May 13 06:10:04 PM      os.kill(pid, signal)
May 13 06:10:04 PM  PermissionError: [Errno 1] Operation not permitted
May 13 06:10:04 PM  
May 13 06:10:04 PM  2023-05-13 10:10:04,683 INFO waiting for steam, beepboop, xvfb, wm, x11vnc to die
May 13 06:10:04 PM  2023-05-13 10:10:04,687 INFO stopped: xvfb (terminated by SIGKILL)
May 13 06:10:04 PM  2023-05-13 10:10:04,868 INFO exited: steam (exit status 1; not expected)
May 13 06:10:04 PM  2023-05-13 10:10:04,869 INFO stopped: x11vnc (exit status 2)
May 13 06:10:04 PM  2023-05-13 10:10:04,875 INFO stopped: wm (exit status 1)
May 13 06:10:04 PM  2023-05-13 10:10:04,876 CRIT unknown problem killing beepboop (28):Traceback (most recent call last):
May 13 06:10:04 PM    File "/usr/lib/python3/dist-packages/supervisor/process.py", line 466, in kill
May 13 06:10:04 PM      options.kill(pid, sig)
May 13 06:10:04 PM    File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1298, in kill
May 13 06:10:04 PM      os.kill(pid, signal)
May 13 06:10:04 PM  PermissionError: [Errno 1] Operation not permitted
```

**Comment by typekcz** [comment]
Looks like Steam exited for some reason.
Check the Steam volume, if the folder exists and Docker has permission to write to it.
